services:
  - type: web
    name: zonke-website
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    region: frankfurt
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        value: onboarding@resend.dev
      - key: RESEND_REPLY_TO
        sync: false
